# -*- coding: utf-8 -*-

# XXX THIS IS JUST A DUPLICATE OF CHARACTERS.JS
# XXX also fix the goddamn indentation

CHARACTER_DETAILS = {
    "1": {
        "acronym": "??",
        "case": "normal",
        "color": "000000",
        "name": "anonymous",
        "option": "Anon/not MSPA",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "10": {
        "acronym": "TG",
        "case": "normal",
        "color": "E00707",
        "name": "turntechGodhead",
        "option": "Dave Strider",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "11": {
        "acronym": "GG",
        "case": "normal",
        "color": "4AC925",
        "name": "gardenGnostic",
        "option": "Jade Harley",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "12": {
        "acronym": "GG",
        "case": "normal",
        "color": "00D5F2",
        "name": "gutsyGumshoe",
        "option": "Jane Crocker",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "13": {
        "acronym": "TG",
        "case": "normal",
        "color": "FF6FF2",
        "name": "tipsyGnostalgic",
        "option": "Roxy Lalonde",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "14": {
        "acronym": "TT",
        "case": "normal",
        "color": "F2A400",
        "name": "timaeusTestified",
        "option": "Dirk Strider",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "15": {
        "acronym": "GT",
        "case": "normal",
        "color": "1F9400",
        "name": "golgothasTerror",
        "option": "Jake English",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "16": {
        "acronym": "TT",
        "case": "normal",
        "color": "E00707",
        "name": "timaeusTestified",
        "option": "Autoresponder",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "17": {
        "acronym": "AA",
        "case": "lower",
        "color": "A10000",
        "name": "apocalypseArisen",
        "option": "Aradia Megido",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['o','0']]"
    },
    "18": {
        "acronym": "AT",
        "case": "inverted",
        "color": "A15000",
        "name": "adiosToreador",
        "option": "Tavros Nitram",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['.',',']]"
    },
    "19": {
        "acronym": "TA",
        "case": "normal",
        "color": "A1A100",
        "name": "twinArmageddons",
        "option": "Sollux Captor",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['I','II'],['i','ii'],['S','2'],['s','2']]"
    },
    "2": {
        "acronym": "**",
        "case": "normal",
        "color": "FF00FF",
        "name": "Original Character",
        "option": "Original character",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "20": {
        "acronym": "CG",
        "case": "upper",
        "color": "626262",
        "name": "carcinoGeneticist",
        "option": "Karkat Vantas",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "21": {
        "acronym": "AC",
        "case": "lower",
        "color": "416600",
        "name": "arsenicCatnip",
        "option": "Nepeta Leijon",
        "quirk_prefix": ":33 < ",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['ee','33']]"
    },
    "22": {
        "acronym": "GA",
        "case": "title",
        "color": "008141",
        "name": "grimAuxiliatrix",
        "option": "Kanaya Maryam",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "23": {
        "acronym": "GC",
        "case": "upper",
        "color": "008282",
        "name": "gallowsCalibrator",
        "option": "Terezi Pyrope",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['A','4'],['E','3'],['I','1']]"
    },
    "24": {
        "acronym": "AG",
        "case": "normal",
        "color": "005682",
        "name": "arachnidsGrip",
        "option": "Vriska Serket",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['B','8'],['b','8']]"
    },
    "25": {
        "acronym": "CT",
        "case": "normal",
        "color": "000056",
        "name": "centaursTesticle",
        "option": "Equius Zahhak",
        "quirk_prefix": "D --> ",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['X','%'],['x','%'],['loo','100'],['ool','001']]"
    },
    "26": {
        "acronym": "TC",
        "case": "alternating",
        "color": "2B0057",
        "name": "terminallyCapricious",
        "option": "Gamzee Makara",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "27": {
        "acronym": "CA",
        "case": "normal",
        "color": "6A006A",
        "name": "caligulasAquarium",
        "option": "Eridan Ampora",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['V','VV'],['v','vv'],['W','WW'],['w','ww']]"
    },
    "28": {
        "acronym": "CC",
        "case": "normal",
        "color": "77003C",
        "name": "cuttlefishCuller",
        "option": "Feferi Peixes",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['E','-E'],['H',')('],['h',')(']]"
    },
    "29": {
        "acronym": "DAMARA",
        "case": "upper",
        "color": "A10000",
        "name": "Damara Megido",
        "option": "Damara Megido",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "3": {
        "acronym": "??",
        "case": "normal",
        "color": "FFAC9F",
        "name": "Trickster",
        "option": "Trickster",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "30": {
        "acronym": "RUFIOH",
        "case": "lower",
        "color": "A15000",
        "name": "Rufioh Nitram",
        "option": "Rufioh Nitram",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['i','1']]"
    },
    "31": {
        "acronym": "MITUNA",
        "case": "upper",
        "color": "A1A100",
        "name": "Mituna Captor",
        "option": "Mituna Captor",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['A','4'],['B','8'],['E','3'],['I','1'],['O','0'],['S','5'],['T','7']]"
    },
    "32": {
        "acronym": "KANKRI",
        "case": "normal",
        "color": "FF0000",
        "name": "Kankri Vantas",
        "option": "Kankri Vantas",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['B','6'],['b','6'],['O','9'],['o','9']]"
    },
    "33": {
        "acronym": "MEULIN",
        "case": "upper",
        "color": "416600",
        "name": "Meulin Leijon",
        "option": "Meulin Leijon",
        "quirk_prefix": "(=\uff40\u03c9\u00b4=) < ",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['EE','33']]"
    },
    "34": {
        "acronym": "PORRIM",
        "case": "normal",
        "color": "008141",
        "name": "Porrim Maryam",
        "option": "Porrim Maryam",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['o','o+']]"
    },
    "35": {
        "acronym": "LATULA",
        "case": "normal",
        "color": "008282",
        "name": "Latula Pyrope",
        "option": "Latula Pyrope",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['A','4'],['a','4'],['E','3'],['e','3'],['I','1'],['i','1']]"
    },
    "36": {
        "acronym": "ARANEA",
        "case": "normal",
        "color": "005682",
        "name": "Aranea Serket",
        "option": "Aranea Serket",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['B','8'],['b','8']]"
    },
    "37": {
        "acronym": "HORUSS",
        "case": "normal",
        "color": "000056",
        "name": "Horuss Zahhak",
        "option": "Horuss Zahhak",
        "quirk_prefix": "8=D < ",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['X','%'],['x','%'],['loo','100'],['ool','001']]"
    },
    "38": {
        "acronym": "KURLOZ",
        "case": "upper",
        "color": "2B0057",
        "name": "Kurloz Makara",
        "option": "Kurloz Makara",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "39": {
        "acronym": "CRONUS",
        "case": "lower",
        "color": "6A006A",
        "name": "Cronus Ampora",
        "option": "Cronus Ampora",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['B','8'],['v','\uf06a'],['w','wv'],['\uf06a','vw']]"
    },
    "4": {
        "acronym": "",
        "case": "normal",
        "color": "FFFFFF",
        "name": "Doc Scratch",
        "option": "Doc Scratch",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "40": {
        "acronym": "MEENAH",
        "case": "normal",
        "color": "77003C",
        "name": "Meenah Peixes",
        "option": "Meenah Peixes",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['E','-E'],['H',')(']]"
    },
    "41": {
        "acronym": "pipefan413",
        "case": "upper",
        "color": "4B4B4B",
        "name": "Dad",
        "option": "Dad",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "42": {
        "acronym": "NANNA",
        "case": "normal",
        "color": "000000",
        "name": "Nanna",
        "option": "Nanna",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "43": {
        "acronym": "MOM",
        "case": "normal",
        "color": "000000",
        "name": "Mom",
        "option": "Mom (pre-scratch)",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "44": {
        "acronym": "BRO",
        "case": "normal",
        "color": "000000",
        "name": "Bro",
        "option": "Bro (pre-scratch)",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "45": {
        "acronym": "GRANDPA",
        "case": "normal",
        "color": "000000",
        "name": "Grandpa",
        "option": "Grandpa",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "46": {
        "acronym": "POPPOP",
        "case": "normal",
        "color": "000000",
        "name": "Poppop",
        "option": "Poppop",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "47": {
        "acronym": "MOM",
        "case": "normal",
        "color": "000000",
        "name": "Mom",
        "option": "Mom (post-scratch)",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "48": {
        "acronym": "BRO",
        "case": "normal",
        "color": "000000",
        "name": "Bro",
        "option": "Bro (post-scratch)",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "49": {
        "acronym": "GRANDMA",
        "case": "normal",
        "color": "000000",
        "name": "Grandma",
        "option": "Grandma",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "5": {
        "acronym": "UU",
        "case": "lower",
        "color": "929292",
        "name": "uranianUmbra",
        "option": "Calliope",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['u','U']]"
    },
    "50": {
        "acronym": "NANNASPRITE",
        "case": "normal",
        "color": "00D5F2",
        "name": "Nannasprite",
        "option": "Nannasprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "51": {
        "acronym": "JASPERSPRITE",
        "case": "normal",
        "color": "F141EF",
        "name": "Jaspersprite",
        "option": "Jaspersprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "52": {
        "acronym": "CALSPRITE",
        "case": "upper",
        "color": "F2A400",
        "name": "Calsprite",
        "option": "Calsprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['A','<'],['B','>'],['C','?'],['D','<'],['E','>'],['F','?'],['G','<'],['H','>'],['I','?'],['J','<'],['K','>'],['L','?'],['M','<'],['N','>'],['O','?'],['P','<'],['Q','>'],['R','?'],['S','<'],['T','>'],['U','?'],['V','<'],['W','>'],['X','?'],['Y','<'],['Z','>'],['<','HAA '],['>','HEE '],['?','HOO ']]"
    },
    "53": {
        "acronym": "DAVESPRITE",
        "case": "lower",
        "color": "F2A400",
        "name": "Davesprite",
        "option": "Davesprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "54": {
        "acronym": "JADESPRITE",
        "case": "normal",
        "color": "1F9400",
        "name": "Jadesprite",
        "option": "Jadesprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "55": {
        "acronym": "TAVRISPRITE",
        "case": "normal",
        "color": "0715CD",
        "name": "Tavrisprite",
        "option": "Tavrisprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "56": {
        "acronym": "FEFETASPRITE",
        "case": "normal",
        "color": "B536DA",
        "name": "Fefetasprite",
        "option": "Fefetasprite",
        "quirk_prefix": "3833 < ",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['E','-E'],['ee','33'],['H',')('],['h',')(']]"
    },
    "57": {
        "acronym": "ERISOLSPRITE",
        "case": "normal",
        "color": "4AC925",
        "name": "Erisolsprite",
        "option": "Erisolsprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['I','II'],['i','ii'],['S','2'],['s','2'],['V','VV'],['v','vv'],['W','WW'],['w','ww']]"
    },
    "58": {
        "acronym": "ARQUIUSPRITE",
        "case": "normal",
        "color": "E00707",
        "name": "Arquiusprite",
        "option": "Arquiusprite",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['I','II'],['i','ii'],['S','2'],['s','2'],['V','VV'],['v','vv'],['W','WW'],['w','ww']]"
    },
    "59": {
        "acronym": "\u2648",
        "case": "normal",
        "color": "A10000",
        "name": "The Handmaid",
        "option": "The Handmaid",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "6": {
        "acronym": "uu",
        "case": "upper",
        "color": "323232",
        "name": "undyingUmbrage",
        "option": "Caliborn",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[['U','u']]"
    },
    "60": {
        "acronym": "\u2649",
        "case": "normal",
        "color": "A15000",
        "name": "The Summoner",
        "option": "The Summoner",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "61": {
        "acronym": "\u264a",
        "case": "normal",
        "color": "A1A100",
        "name": "The \u03a8iioniic",
        "option": "The \u03a8iioniic",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "62": {
        "acronym": "\u264b",
        "case": "normal",
        "color": "626262",
        "name": "The Signless",
        "option": "The Signless",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "63": {
        "acronym": "\u264c",
        "case": "normal",
        "color": "416600",
        "name": "The Disciple",
        "option": "The Disciple",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "64": {
        "acronym": "\u264d",
        "case": "normal",
        "color": "008141",
        "name": "The Dolorosa",
        "option": "The Dolorosa",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "65": {
        "acronym": "\u264e",
        "case": "normal",
        "color": "008282",
        "name": "Neophyte Redglare",
        "option": "Neophyte Redglare",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "66": {
        "acronym": "\u264f",
        "case": "normal",
        "color": "005682",
        "name": "Marquise Spinneret Mindfang",
        "option": "Marquise Spinneret Mindfang",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "67": {
        "acronym": "\u2650",
        "case": "normal",
        "color": "000056",
        "name": "E%ecutor Darkleer",
        "option": "E%ecutor Darkleer",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "68": {
        "acronym": "\u2651",
        "case": "normal",
        "color": "2B0057",
        "name": "The Grand Highblood",
        "option": "The Grand Highblood",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "69": {
        "acronym": "\u2652",
        "case": "normal",
        "color": "6A006A",
        "name": "Orphaner Dualscar",
        "option": "Orphaner Dualscar",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "7": {
        "acronym": "??",
        "case": "normal",
        "color": "ff83fb",
        "name": "Other MSPA",
        "option": "Other MSPA",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "70": {
        "acronym": "\u2653",
        "case": "normal",
        "color": "77003C",
        "name": "Her Imperious Condescension",
        "option": "Her Imperious Condescension",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "71": {
        "acronym": "\u2660",
        "case": "normal",
        "color": "000000",
        "name": "Spades Slick",
        "option": "Spades Slick",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "72": {
        "acronym": "\u2663",
        "case": "normal",
        "color": "000000",
        "name": "Clubs Deuce",
        "option": "Clubs Deuce",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "73": {
        "acronym": "\u2666",
        "case": "normal",
        "color": "000000",
        "name": "Diamonds Droog",
        "option": "Diamonds Droog",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "74": {
        "acronym": "\u2665",
        "case": "normal",
        "color": "000000",
        "name": "Hearts Boxcars",
        "option": "Hearts Boxcars",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "75": {
        "acronym": "WV",
        "case": "normal",
        "color": "000000",
        "name": "Wayward Vagabond",
        "option": "Wayward Vagabond",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "76": {
        "acronym": "PM",
        "case": "normal",
        "color": "000000",
        "name": "Parcel Mistress",
        "option": "Parcel Mistress",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "77": {
        "acronym": "AR",
        "case": "normal",
        "color": "000000",
        "name": "Aimless Renegade",
        "option": "Aimless Renegade",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "78": {
        "acronym": "WQ",
        "case": "normal",
        "color": "000000",
        "name": "Windswept Questant",
        "option": "Windswept Questant",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "79": {
        "acronym": "JN",
        "case": "normal",
        "color": "000000",
        "name": "Jack Noir",
        "option": "Jack Noir",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "8": {
        "acronym": "EB",
        "case": "normal",
        "color": "0715CD",
        "name": "ectoBiologist",
        "option": "John Egbert",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "80": {
        "acronym": "DD",
        "case": "normal",
        "color": "000000",
        "name": "Draconian Dignitary",
        "option": "Draconian Dignitary",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "81": {
        "acronym": "HB",
        "case": "normal",
        "color": "000000",
        "name": "Hegemonic Brute",
        "option": "Hegemonic Brute",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "82": {
        "acronym": "CD",
        "case": "normal",
        "color": "000000",
        "name": "Courtyard Droll",
        "option": "Courtyard Droll",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "83": {
        "acronym": "LE",
        "case": "normal",
        "color": "2ED73A",
        "name": "Lord English",
        "option": "Lord English",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "84": {
        "acronym": "08",
        "case": "normal",
        "color": "000000",
        "name": "Snowman",
        "option": "Snowman",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "85": {
        "acronym": "MP",
        "case": "normal",
        "color": "000000",
        "name": "Ms. Paint",
        "option": "Ms. Paint",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "86": {
        "acronym": "AH",
        "case": "normal",
        "color": "000000",
        "name": "Andrew Hussie",
        "option": "Andrew Hussie",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    },
    "9": {
        "acronym": "TT",
        "case": "normal",
        "color": "B536DA",
        "name": "tentacleTherapist",
        "option": "Rose Lalonde",
        "quirk_prefix": "",
        "quirk_suffix": "",
        "regexes": "[]",
        "replacements": "[]"
    }
}

GROUP_DETAILS = {
    "1": {
        "name": "Agents of Derse",
        "character": set(["79", "80", "81", "82"]),
    },
    "10": {
        "name": "Kids",
        "character": set(["8", "9", "10", "11", "12", "13", "14", "15", "16", "53", "54"]),
    },
    "11": {
        "name": "Kids (post-scratch)",
        "character": set(["12", "13", "14", "15", "16"]),
    },
    "12": {
        "name": "Kids (pre-scratch)",
        "character": set(["8", "9", "10", "11", "53", "54"]),
    },
    "13": {
        "name": "Lalondes",
        "character": set(["9", "13", "43", "47"]),
    },
    "14": {
        "name": "Midnight Crew",
        "character": set(["71", "72", "73", "74"]),
    },
    "15": {
        "name": "Prospitians",
        "character": set(["76", "78", "85"]),
    },
    "16": {
        "name": "Sprites",
        "character": set(["50", "51", "52", "53", "54", "55", "56", "57", "58"]),
    },
    "17": {
        "name": "Sprites (post-scratch)",
        "character": set(["55", "56", "57", "58"]),
    },
    "18": {
        "name": "Sprites (pre-scratch)",
        "character": set(["50", "51", "52", "53", "54"]),
    },
    "19": {
        "name": "Striders",
        "character": set(["10", "14", "16", "44", "48", "53"]),
    },
    "2": {
        "name": "Ancestors",
        "character": set(["59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70"]),
    },
    "20": {
        "name": "Trolls",
        "character": set(["17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40"]),
    },
    "21": {
        "name": "Trolls (post-scratch)",
        "character": set(["17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"]),
    },
    "22": {
        "name": "Trolls (pre-scratch)",
        "character": set(["29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40"]),
    },
    "3": {
        "name": "Carapaces",
        "character": set(["71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "84", "85"]),
    },
    "4": {
        "name": "Cherubs",
        "character": set(["5", "6"]),
    },
    "5": {
        "name": "Dersites",
        "character": set(["71", "72", "73", "74", "75", "77", "79", "80", "81", "82", "84"]),
    },
    "6": {
        "name": "Exiles",
        "character": set(["75", "76", "77", "78"]),
    },
    "7": {
        "name": "Guardians",
        "character": set(["41", "42", "43", "44", "45", "46", "47", "48", "49"]),
    },
    "8": {
        "name": "Guardians (post-scratch)",
        "character": set(["41", "46", "47", "48", "49"]),
    },
    "9": {
        "name": "Guardians (pre-scratch)",
        "character": set(["41", "42", "43", "44", "45"]),
    },
}

SORTED_CHARACTERS = sorted(CHARACTER_DETAILS.keys(), key=lambda _: CHARACTER_DETAILS[_]['option'])
SORTED_GROUPS = sorted(GROUP_DETAILS.keys(), key=lambda _: GROUP_DETAILS[_]['name'])
